services:
  # FastAPI Backend Service
  - type: web
    name: flex-living-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: flex-living-db
          property: connectionString
      - key: HOSTAWAY_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false

databases:
  # PostgreSQL Database
  - name: flex-living-db
    databaseName: flex_living
    plan: free
    region: oregon
